server:
  port: 8101
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://j9d110.p.ssafy.io:8761/eureka/

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://j9d110.p.ssafy.io:8102
          predicates:
            - Path=/user-service/**
          filters:
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        - id: news-service
          uri: http://j9d110.p.ssafy.io:8200
          predicates:
            - Path=/news-service/**
          filters:
            - RewritePath=/news-service/(?<segment>.*), /$\{segment}
        - id: invest-service
          uri: lb://INVEST-SERVICE
          predicates:
            - Path=/invest-service/**
          filters:
            - RewritePath=/invest-service/(?<segment>.*), /$\{segment}
