server:
  port: 8082

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defalutZone: http://localhost:8761/eureka

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      routes:
        - id: client-service
          uri: lb://CLIENT-SERVICE
          predicates:
            - Path=/client-service/**
          filters:
            - RewritePath=/client-service/(?<segment>.*), /$\{segment}