server:
  port: 8081

spring:
  application:
    name: discoveryservice # ??? ID

eureka:
  client:
    register-with-eureka: false # default : true
    fetch-registry: false # default : true

# Eureka Libray? ????? ??? ????? Eureka Client?? ???? ???? ??? ???????.
# ??? true? ???? ?? ??? ??? ???? ???? ???? ??? ?? ????? false? ?? ?????.