#spring:
#  profiles:
#    active: prod
#  application:
#    name: invest
#  config:
#    import: optional:configserver:http://j9d110.p.ssafy.io:9090
server:
  port: 8105
spring:
  profiles:
    active: dev
  config:
    import: optional:configserver:http://j9d110.p.ssafy.io:9090
  application:
    name: trading
  rabbitmq:
    host: 13.124.168.191
    port: 5672
    username: jrjr
    password: wnfjdwnfjd
  datasource:
    url: jdbc:mariadb://j9d110.p.ssafy.io:3306/jrjr?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    driverClassName: org.mariadb.jdbc.Driver
    username: jrjr
    password: wnfjdwnfjd
#    hikari:
#      maximum-pool-size: 1
  jpa:
    hibernate:
      ddl-auto: update
      show_sql: true
  data:
    mongodb:
      uri: mongodb+srv://S09P22D110:KbnJjY3PZQ@ssafy.ngivl.mongodb.net/S09P22D110?authSource=admin
    redis:
      host: j9d110.p.ssafy.io
      port: 6380
      password: wnfjdwnfjd
  devtools:
    livereload:
      enabled: false
    restart:
      enabled: false
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://j9d110.p.ssafy.io:8761/eureka
  instance:
    hostname: j9d110.p.ssafy.io
    instance-id: ${spring.application.name}-${server.port}
management:
  endpoints:
    web:
      exposure:
        include:
          - "*"
      base-path : /inbest
  endpoint:
    gateway:
      enabled: true

stock:
  url:
    market-price: https://markets.hankyung.com/stock/
